"""empty message

Revision ID: 670955f59b1c
Revises: 88e596c0fa5e
Create Date: 2024-03-19 17:37:09.812180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '670955f59b1c'
down_revision = '88e596c0fa5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
