"""empty message

Revision ID: 88e596c0fa5e
Revises: 3fd884f04bd3
Create Date: 2024-03-18 13:32:46.247931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88e596c0fa5e'
down_revision = '3fd884f04bd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customer', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customer', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
